<?php
    $xmlNFSE = '
        <Envio>
            <ModeloDocumento>NFSe</ModeloDocumento>
            <Versao>1.00</Versao>
            <RPS>
                <RPSNumero>'.$nfse->rpsnumero.'</RPSNumero>
                <RPSSerie>'.$nfse->rpsserie.'</RPSSerie>
                <RPSTipo>'.$nfse->rpstipo.'</RPSTipo>
                <dEmis>'.$nfse->demis.'T00:00:00</dEmis>
                <natOp>'.$nfse->natop.'</natOp>
                <RegEspTrib>'.$nfse->regesptrib.'</RegEspTrib>
                <OptSN>'.$nfse->optsn.'</OptSN>
                <IncCult>'.$nfse->inccuilt.'</IncCult>
                <Status>1</Status>
                <tpAmb>'.$env.'</tpAmb>
                <Prestador>
                    <CNPJ_prest>83248021000158</CNPJ_prest>
                    <IM>001169</IM>
                </Prestador>
                <Servico>
                    <Valores>
                        <ValServicos>'.$servicos->valservicos.'</ValServicos>
                        <ValDeducoes>'.$servicos->valdeducoes.'</ValDeducoes>
                        <ValPIS>'.$servicos->valpis.'</ValPIS>
                        <ValCOFINS>'.$servicos->valcofins.'</ValCOFINS>
                        <ValINSS>'.$servicos->valinss.'</ValINSS>
                        <ValIR>'.$servicos->valir.'</ValIR>
                        <ValCSLL>'.$servicos->valcsll.'</ValCSLL>
                        <ISSRetido>'.$servicos->issretido.'</ISSRetido>
                        <RespRetencao/>
                        <ValISS>'.$servicos->valiss.'</ValISS>
                        <ValISSRetido/>
                        <ValBaseCalculo>'.$servicos->valbasecalculo.'</ValBaseCalculo>
                        <ValOutrasRetencoes>'.$servicos->valoutrasretencoes.'</ValOutrasRetencoes>
                        <ValAliqISS>'.$servicos->valaliqiss.'</ValAliqISS>
                        <ValDescIncond>'.$servicos->valdescincond.'</ValDescIncond>
                        <ValDescCond>'.$servicos->valdesccond.'</ValDescCond>
                    </Valores>
                    <IteListServico>'.$servicos->itelistserv.'</IteListServico>
                    <TributMunicipio>1401</TributMunicipio>
                    <Discriminacao>'.$item->discriminacao.'</Discriminacao>
                    <cMunIncidencia>'.$item->cmunincidencia.'</cMunIncidencia>
                    <cMun>'.$servicos->cmun.'</cMun>
                </Servico>
                <Tomador>
                    <TomaCNPJ>'.$tomador->tomacnpj.'</TomaCNPJ>
                    <TomaCPF>'.$tomador->tomacpf.'</TomaCPF>
                    <TomaIM>'.$tomador->tomaim.'</TomaIM>
                    <TomaRazaoSocial>'.$tomador->tomarazaosocial.'</TomaRazaoSocial>
                    <TomatpLgr>'.$tomador->tomatplgr.'</TomatpLgr>
                    <TomaEndereco>'.$tomador->tomaendereco.'</TomaEndereco>
                    <TomaNumero>'.$tomador->tomanumero.'</TomaNumero>
                    <TomaComplemento>'.$tomador->tomacomplemento.'</TomaComplemento>
                    <TomaBairro>'.$tomador->tomabairro.'</TomaBairro>
                    <TomacMun>'.$tomador->tomacmun.'</TomacMun>
                    <TomaxMun>'.$tomador->tomaxmun.'</TomaxMun>
                    <TomaUF>'.$tomador->tomars.'</TomaUF>
                    <TomaCEP>'.$tomador->tomacep.'</TomaCEP>
                    <TomaEmail>'.$tomador->tomaemail.'</TomaEmail>
                </Tomador>
            </RPS>
        </Envio>
    ';