<?php
	$entidadeNome = PREFIXO . "erp_geral_pais";
	
	inserirRegistro($conn,$entidadeNome,1, array("nome"), array("'Afeganistão'"));
	inserirRegistro($conn,$entidadeNome,2, array("nome"), array("'África do Sul'"));
	inserirRegistro($conn,$entidadeNome,3, array("nome"), array("'Albânia'"));
	inserirRegistro($conn,$entidadeNome,4, array("nome"), array("'Alemanha'"));
	inserirRegistro($conn,$entidadeNome,5, array("nome"), array("'Andorra'"));
	inserirRegistro($conn,$entidadeNome,6, array("nome"), array("'Angola'"));
	inserirRegistro($conn,$entidadeNome,7, array("nome"), array("'Antiga e Barbuda'"));
	inserirRegistro($conn,$entidadeNome,8, array("nome"), array("'Arábia Saudita'"));
	inserirRegistro($conn,$entidadeNome,9, array("nome"), array("'Argélia'"));
	inserirRegistro($conn,$entidadeNome,10, array("nome"), array("'Argentina'"));
	inserirRegistro($conn,$entidadeNome,11, array("nome"), array("'Arménia'"));
	inserirRegistro($conn,$entidadeNome,12, array("nome"), array("'Austrália'"));
	inserirRegistro($conn,$entidadeNome,13, array("nome"), array("'Áustria'"));
	inserirRegistro($conn,$entidadeNome,14, array("nome"), array("'Azerbaijão'"));
	inserirRegistro($conn,$entidadeNome,15, array("nome"), array("'Bahamas'"));
	inserirRegistro($conn,$entidadeNome,16, array("nome"), array("'Bangladexe'"));
	inserirRegistro($conn,$entidadeNome,17, array("nome"), array("'Barbados'"));
	inserirRegistro($conn,$entidadeNome,18, array("nome"), array("'Barém'"));
	inserirRegistro($conn,$entidadeNome,19, array("nome"), array("'Bélgica'"));
	inserirRegistro($conn,$entidadeNome,20, array("nome"), array("'Belize'"));
	inserirRegistro($conn,$entidadeNome,21, array("nome"), array("'Benim'"));
	inserirRegistro($conn,$entidadeNome,22, array("nome"), array("'Bielorrússia'"));
	inserirRegistro($conn,$entidadeNome,23, array("nome"), array("'Bolívia'"));
	inserirRegistro($conn,$entidadeNome,24, array("nome"), array("'Bósnia e Herzegovina'"));
	inserirRegistro($conn,$entidadeNome,25, array("nome"), array("'Botsuana'"));
	inserirRegistro($conn,$entidadeNome,26, array("nome"), array("'Brasil'"));
	inserirRegistro($conn,$entidadeNome,27, array("nome"), array("'Brunei'"));
	inserirRegistro($conn,$entidadeNome,28, array("nome"), array("'Bulgária'"));
	inserirRegistro($conn,$entidadeNome,29, array("nome"), array("'Burquina Faso'"));
	inserirRegistro($conn,$entidadeNome,30, array("nome"), array("'Burúndi'"));
	inserirRegistro($conn,$entidadeNome,31, array("nome"), array("'Butão'"));
	inserirRegistro($conn,$entidadeNome,32, array("nome"), array("'Cabo Verde'"));
	inserirRegistro($conn,$entidadeNome,33, array("nome"), array("'Camarões'"));
	inserirRegistro($conn,$entidadeNome,34, array("nome"), array("'Camboja'"));
	inserirRegistro($conn,$entidadeNome,35, array("nome"), array("'Canadá'"));
	inserirRegistro($conn,$entidadeNome,36, array("nome"), array("'Catar'"));
	inserirRegistro($conn,$entidadeNome,37, array("nome"), array("'Cazaquistão'"));
	inserirRegistro($conn,$entidadeNome,38, array("nome"), array("'Chade'"));
	inserirRegistro($conn,$entidadeNome,39, array("nome"), array("'Chile'"));
	inserirRegistro($conn,$entidadeNome,40, array("nome"), array("'China'"));
	inserirRegistro($conn,$entidadeNome,41, array("nome"), array("'Chipre'"));
	inserirRegistro($conn,$entidadeNome,42, array("nome"), array("'Colômbia'"));
	inserirRegistro($conn,$entidadeNome,43, array("nome"), array("'Comores'"));
	inserirRegistro($conn,$entidadeNome,44, array("nome"), array("'Congo-Brazzaville'"));
	inserirRegistro($conn,$entidadeNome,45, array("nome"), array("'Coreia do Norte'"));
	inserirRegistro($conn,$entidadeNome,46, array("nome"), array("'Coreia do Sul'"));
	inserirRegistro($conn,$entidadeNome,47, array("nome"), array("'Cosovo'"));
	inserirRegistro($conn,$entidadeNome,48, array("nome"), array("'Costa do Marfim'"));
	inserirRegistro($conn,$entidadeNome,49, array("nome"), array("'Costa Rica'"));
	inserirRegistro($conn,$entidadeNome,50, array("nome"), array("'Croácia'"));
	inserirRegistro($conn,$entidadeNome,51, array("nome"), array("'Cuaite'"));
	inserirRegistro($conn,$entidadeNome,52, array("nome"), array("'Cuba'"));
	inserirRegistro($conn,$entidadeNome,53, array("nome"), array("'Dinamarca'"));
	inserirRegistro($conn,$entidadeNome,54, array("nome"), array("'Dominica'"));
	inserirRegistro($conn,$entidadeNome,55, array("nome"), array("'Egito'"));
	inserirRegistro($conn,$entidadeNome,56, array("nome"), array("'Emirados Árabes'"));
	inserirRegistro($conn,$entidadeNome,57, array("nome"), array("'Equador'"));
	inserirRegistro($conn,$entidadeNome,58, array("nome"), array("'Eritreia'"));
	inserirRegistro($conn,$entidadeNome,59, array("nome"), array("'Eslováquia'"));
	inserirRegistro($conn,$entidadeNome,60, array("nome"), array("'Eslovénia'"));
	inserirRegistro($conn,$entidadeNome,61, array("nome"), array("'Espanha'"));
	inserirRegistro($conn,$entidadeNome,62, array("nome"), array("'Estado da Palestina'"));
	inserirRegistro($conn,$entidadeNome,63, array("nome"), array("'Estados Unidos'"));
	inserirRegistro($conn,$entidadeNome,64, array("nome"), array("'Estónia'"));
	inserirRegistro($conn,$entidadeNome,65, array("nome"), array("'Etiópia'"));
	inserirRegistro($conn,$entidadeNome,66, array("nome"), array("'Fiji'"));
	inserirRegistro($conn,$entidadeNome,67, array("nome"), array("'Filipinas'"));
	inserirRegistro($conn,$entidadeNome,68, array("nome"), array("'Finlândia'"));
	inserirRegistro($conn,$entidadeNome,69, array("nome"), array("'França'"));
	inserirRegistro($conn,$entidadeNome,70, array("nome"), array("'Gabão'"));
	inserirRegistro($conn,$entidadeNome,71, array("nome"), array("'Gâmbia'"));
	inserirRegistro($conn,$entidadeNome,72, array("nome"), array("'Gana'"));
	inserirRegistro($conn,$entidadeNome,73, array("nome"), array("'Geórgia'"));
	inserirRegistro($conn,$entidadeNome,74, array("nome"), array("'Granada'"));
	inserirRegistro($conn,$entidadeNome,75, array("nome"), array("'Grécia'"));
	inserirRegistro($conn,$entidadeNome,76, array("nome"), array("'Guatemala'"));
	inserirRegistro($conn,$entidadeNome,77, array("nome"), array("'Guiana'"));
	inserirRegistro($conn,$entidadeNome,78, array("nome"), array("'Guiné'"));
	inserirRegistro($conn,$entidadeNome,79, array("nome"), array("'Guiné Equatorial'"));
	inserirRegistro($conn,$entidadeNome,80, array("nome"), array("'Guiné-Bissau'"));
	inserirRegistro($conn,$entidadeNome,81, array("nome"), array("'Haiti'"));
	inserirRegistro($conn,$entidadeNome,82, array("nome"), array("'Honduras'"));
	inserirRegistro($conn,$entidadeNome,83, array("nome"), array("'Hungria'"));
	inserirRegistro($conn,$entidadeNome,84, array("nome"), array("'Iémen'"));
	inserirRegistro($conn,$entidadeNome,85, array("nome"), array("'Ilhas Marechal'"));
	inserirRegistro($conn,$entidadeNome,86, array("nome"), array("'Índia'"));
	inserirRegistro($conn,$entidadeNome,87, array("nome"), array("'Indonésia'"));
	inserirRegistro($conn,$entidadeNome,88, array("nome"), array("'Irão'"));
	inserirRegistro($conn,$entidadeNome,89, array("nome"), array("'Iraque'"));
	inserirRegistro($conn,$entidadeNome,90, array("nome"), array("'Irlanda'"));
	inserirRegistro($conn,$entidadeNome,91, array("nome"), array("'Islândia'"));
	inserirRegistro($conn,$entidadeNome,92, array("nome"), array("'Israel'"));
	inserirRegistro($conn,$entidadeNome,93, array("nome"), array("'Itália'"));
	inserirRegistro($conn,$entidadeNome,94, array("nome"), array("'Jamaica'"));
	inserirRegistro($conn,$entidadeNome,95, array("nome"), array("'Japão'"));
	inserirRegistro($conn,$entidadeNome,96, array("nome"), array("'Jibuti'"));
	inserirRegistro($conn,$entidadeNome,97, array("nome"), array("'Jordânia'"));
	inserirRegistro($conn,$entidadeNome,98, array("nome"), array("'Laus'"));
	inserirRegistro($conn,$entidadeNome,99, array("nome"), array("'Lesoto'"));
	inserirRegistro($conn,$entidadeNome,100, array("nome"), array("'Letónia'"));
	inserirRegistro($conn,$entidadeNome,101, array("nome"), array("'Líbano'"));
	inserirRegistro($conn,$entidadeNome,102, array("nome"), array("'Libéria'"));
	inserirRegistro($conn,$entidadeNome,103, array("nome"), array("'Líbia'"));
	inserirRegistro($conn,$entidadeNome,104, array("nome"), array("'Listenstaine'"));
	inserirRegistro($conn,$entidadeNome,105, array("nome"), array("'Lituânia'"));
	inserirRegistro($conn,$entidadeNome,106, array("nome"), array("'Luxemburgo'"));
	inserirRegistro($conn,$entidadeNome,107, array("nome"), array("'Macedónia'"));
	inserirRegistro($conn,$entidadeNome,108, array("nome"), array("'Madagáscar'"));
	inserirRegistro($conn,$entidadeNome,109, array("nome"), array("'Malásia'"));
	inserirRegistro($conn,$entidadeNome,110, array("nome"), array("'Maláui'"));
	inserirRegistro($conn,$entidadeNome,111, array("nome"), array("'Maldivas'"));
	inserirRegistro($conn,$entidadeNome,112, array("nome"), array("'Mali'"));
	inserirRegistro($conn,$entidadeNome,113, array("nome"), array("'Malta'"));
	inserirRegistro($conn,$entidadeNome,114, array("nome"), array("'Marrocos'"));
	inserirRegistro($conn,$entidadeNome,115, array("nome"), array("'Maurícia'"));
	inserirRegistro($conn,$entidadeNome,116, array("nome"), array("'Mauritânia'"));
	inserirRegistro($conn,$entidadeNome,117, array("nome"), array("'México'"));
	inserirRegistro($conn,$entidadeNome,118, array("nome"), array("'Mianmar'"));
	inserirRegistro($conn,$entidadeNome,119, array("nome"), array("'Micronésia'"));
	inserirRegistro($conn,$entidadeNome,120, array("nome"), array("'Moçambique'"));
	inserirRegistro($conn,$entidadeNome,121, array("nome"), array("'Moldávia'"));
	inserirRegistro($conn,$entidadeNome,122, array("nome"), array("'Mónaco'"));
	inserirRegistro($conn,$entidadeNome,123, array("nome"), array("'Mongólia'"));
	inserirRegistro($conn,$entidadeNome,124, array("nome"), array("'Montenegro'"));
	inserirRegistro($conn,$entidadeNome,125, array("nome"), array("'Namíbia'"));
	inserirRegistro($conn,$entidadeNome,126, array("nome"), array("'Nauru'"));
	inserirRegistro($conn,$entidadeNome,127, array("nome"), array("'Nepal'"));
	inserirRegistro($conn,$entidadeNome,128, array("nome"), array("'Nicarágua'"));
	inserirRegistro($conn,$entidadeNome,129, array("nome"), array("'Níger'"));
	inserirRegistro($conn,$entidadeNome,130, array("nome"), array("'Nigéria'"));
	inserirRegistro($conn,$entidadeNome,131, array("nome"), array("'Noruega'"));
	inserirRegistro($conn,$entidadeNome,132, array("nome"), array("'Nova Zelândia'"));
	inserirRegistro($conn,$entidadeNome,133, array("nome"), array("'Omã'"));
	inserirRegistro($conn,$entidadeNome,134, array("nome"), array("'Países Baixos'"));
	inserirRegistro($conn,$entidadeNome,135, array("nome"), array("'Palau'"));
	inserirRegistro($conn,$entidadeNome,136, array("nome"), array("'Panamá'"));
	inserirRegistro($conn,$entidadeNome,137, array("nome"), array("'Papua Nova Guiné'"));
	inserirRegistro($conn,$entidadeNome,138, array("nome"), array("'Paquistão'"));
	inserirRegistro($conn,$entidadeNome,139, array("nome"), array("'Paraguai'"));
	inserirRegistro($conn,$entidadeNome,140, array("nome"), array("'Peru'"));
	inserirRegistro($conn,$entidadeNome,141, array("nome"), array("'Polónia'"));
	inserirRegistro($conn,$entidadeNome,142, array("nome"), array("'Portugal'"));
	inserirRegistro($conn,$entidadeNome,143, array("nome"), array("'Quénia'"));
	inserirRegistro($conn,$entidadeNome,144, array("nome"), array("'Quirguistão'"));
	inserirRegistro($conn,$entidadeNome,145, array("nome"), array("'Quiribáti'"));
	inserirRegistro($conn,$entidadeNome,146, array("nome"), array("'Reino Unido'"));
	inserirRegistro($conn,$entidadeNome,147, array("nome"), array("'República'"));
	inserirRegistro($conn,$entidadeNome,148, array("nome"), array("'República Checa'"));
	inserirRegistro($conn,$entidadeNome,149, array("nome"), array("'República Democrática do Congo'"));
	inserirRegistro($conn,$entidadeNome,150, array("nome"), array("'República Dominicana'"));
	inserirRegistro($conn,$entidadeNome,151, array("nome"), array("'Roménia'"));
	inserirRegistro($conn,$entidadeNome,152, array("nome"), array("'Ruanda'"));
	inserirRegistro($conn,$entidadeNome,153, array("nome"), array("'Rússia'"));
	inserirRegistro($conn,$entidadeNome,154, array("nome"), array("'Salomão'"));
	inserirRegistro($conn,$entidadeNome,155, array("nome"), array("'Salvador'"));
	inserirRegistro($conn,$entidadeNome,156, array("nome"), array("'Samoa'"));
	inserirRegistro($conn,$entidadeNome,157, array("nome"), array("'Santa Lúcia'"));
	inserirRegistro($conn,$entidadeNome,158, array("nome"), array("'São Cristóvão e Neves'"));
	inserirRegistro($conn,$entidadeNome,159, array("nome"), array("'São Marinho'"));
	inserirRegistro($conn,$entidadeNome,160, array("nome"), array("'São Tomé e Príncipe'"));
	inserirRegistro($conn,$entidadeNome,161, array("nome"), array("'São Vicente e Granadinas'"));
	inserirRegistro($conn,$entidadeNome,162, array("nome"), array("'Seicheles'"));
	inserirRegistro($conn,$entidadeNome,163, array("nome"), array("'Senegal'"));
	inserirRegistro($conn,$entidadeNome,164, array("nome"), array("'Serra Leoa'"));
	inserirRegistro($conn,$entidadeNome,165, array("nome"), array("'Sérvia'"));
	inserirRegistro($conn,$entidadeNome,166, array("nome"), array("'Singapura'"));
	inserirRegistro($conn,$entidadeNome,167, array("nome"), array("'Síria'"));
	inserirRegistro($conn,$entidadeNome,168, array("nome"), array("'Somália'"));
	inserirRegistro($conn,$entidadeNome,169, array("nome"), array("'Sri Lanca'"));
	inserirRegistro($conn,$entidadeNome,170, array("nome"), array("'Suazilândia'"));
	inserirRegistro($conn,$entidadeNome,171, array("nome"), array("'Sudão'"));
	inserirRegistro($conn,$entidadeNome,172, array("nome"), array("'Sudão do Sul'"));
	inserirRegistro($conn,$entidadeNome,173, array("nome"), array("'Suécia'"));
	inserirRegistro($conn,$entidadeNome,174, array("nome"), array("'Suíça'"));
	inserirRegistro($conn,$entidadeNome,175, array("nome"), array("'Suriname'"));
	inserirRegistro($conn,$entidadeNome,176, array("nome"), array("'Tailândia'"));
	inserirRegistro($conn,$entidadeNome,177, array("nome"), array("'Taiuã'"));
	inserirRegistro($conn,$entidadeNome,178, array("nome"), array("'Tajiquistão'"));
	inserirRegistro($conn,$entidadeNome,179, array("nome"), array("'Tanzânia'"));
	inserirRegistro($conn,$entidadeNome,180, array("nome"), array("'Timor-Leste'"));
	inserirRegistro($conn,$entidadeNome,181, array("nome"), array("'Togo'"));
	inserirRegistro($conn,$entidadeNome,182, array("nome"), array("'Tonga'"));
	inserirRegistro($conn,$entidadeNome,183, array("nome"), array("'Trindade e Tobago'"));
	inserirRegistro($conn,$entidadeNome,184, array("nome"), array("'Tunísia'"));
	inserirRegistro($conn,$entidadeNome,185, array("nome"), array("'Turcomenistão'"));
	inserirRegistro($conn,$entidadeNome,186, array("nome"), array("'Turquia'"));
	inserirRegistro($conn,$entidadeNome,187, array("nome"), array("'Tuvalu'"));
	inserirRegistro($conn,$entidadeNome,188, array("nome"), array("'Ucrânia'"));
	inserirRegistro($conn,$entidadeNome,189, array("nome"), array("'Uganda'"));
	inserirRegistro($conn,$entidadeNome,190, array("nome"), array("'Uruguai'"));
	inserirRegistro($conn,$entidadeNome,191, array("nome"), array("'Usbequistão'"));
	inserirRegistro($conn,$entidadeNome,192, array("nome"), array("'Vanuatu'"));
	inserirRegistro($conn,$entidadeNome,193, array("nome"), array("'Vaticano'"));
	inserirRegistro($conn,$entidadeNome,194, array("nome"), array("'Venezuela'"));
	inserirRegistro($conn,$entidadeNome,195, array("nome"), array("'Vietname'"));
	inserirRegistro($conn,$entidadeNome,196, array("nome"), array("'Zâmbia'"));
	inserirRegistro($conn,$entidadeNome,197, array("nome"), array("'Zimbábue'"));